import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Layout } from "./layout/Layout";
import AuthContextProvider from "./context/AuthContext";
import CartContextProvider from "./context/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Tesla Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthContextProvider>
          <CartContextProvider>
            <Layout>
            {children}
            </Layout>
          </CartContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
